syntax = "proto3";

package SkillBridge.Message;

option csharp_namespace = "SkillBridge.Message";
option cc_enable_arenas = true;

////////////////////////////////////////////////////////////////
//
//  Basic Defines  每次加完协议MessageDispatch里加消息分发
//
////////////////////////////////////////////////////////////////
enum RESULT
{
	SUCCESS = 0;
	FAILED = 1;
}

enum CHARACTER_TYPE
{
	Player = 0;
	NPC = 1;
	Monster = 2;
}

enum CHARACTER_CLASS
{
	NONE = 0;
	WARRIOR = 1;
	WIZARD = 2;
	ARCHER = 3;
}

enum CHARACTER_STATE
{
	IDLE = 0;
	MOVE = 1;
	RUN=2;
}

enum ENTITY_EVENT
{
	EVENT_NONE = 0;
    EVENT_IDLE = 1;
    EVENT_MOVE = 2;
    EVENT_JUMP = 3;
	EVENT_RUN = 4;
	EVENT_RIDE=5;
}

enum ITEM_TYPE
{
	NORMAL=0;
	MATERIAL=1;//材料
	TASK=2; //任务道具
	EQUIP=3;//装备
	PUPPY=4;//宠物
	RIDE=5;//坐骑
}

enum EQUIP_SLOT
{
	WEAPON=0;//武器
	ACCESSORY=1;//防具
	HELMET=2;//头盔
	CHEST=3;//胸甲
	SHOULDER=4;//护肩
	PANTS=5;//裤子
	BOOTS=6;//靴子
	SLOT_MAX=7;//槽位上限7个
}

message NUserInfo {
	int32 id = 1;
	NPlayerInfo player = 2;
}

message NPlayerInfo {
	int32 id = 1;
	repeated NCharacterInfo characters = 2;
}

message NCharacterInfo {
	int32 id = 1;//db id  数据库ID
	int32 config_id = 2;//config id  配置表ID
	int32 entity_id = 3;//entity id  实体ID
	string name = 4;
	CHARACTER_TYPE type = 5;
	CHARACTER_CLASS class = 6;
	int32 level = 7;
	int32 mapId = 8;
	NEntity entity = 9; 
	int64 gold=10;
	repeated NItemInfo Items=11;//背包列表
	NBagInfo Bag=12; //背包系统
	bytes Equips=13;//装备
	repeated NQuestInfo quests=14;//任务列表
	repeated NFriendInfo friends=15;//好友系统
	NGuildInfo guild=16;//公会
	int32 ride=17;//坐骑id
}

message NItemInfo
{
	int32 id=1;
	int32 count=2;
}

message NVector3
{
	int32 x = 1;
	int32 y = 2;
	int32 z = 3;
}

message NBagInfo
{
	int32 Unlocked=1;//解锁的格子数
	bytes Items=2;//背包里放的道具 字节类型 长度不一定 长度为4*Unlocked的数量
}

////////////////////////////////////////////////////////////////
//
//  状态
//
////////////////////////////////////////////////////////////////

enum STATUS_ACTION
{
	UPDATE=0;//状态更新
	ADD=1;//增加
	DELETE=2;//删除
}

enum STATUS_TYPE//状态改变的具体内容
{
	MONEY=0;
	EXP=1;
	SKILL_POINT=2;
	ITEM=3;
}

enum STATUS_SOURCE
{
	UPDATE=0;
	ADD=1;
	DELETE=2;
}

message NSTATUS
{
	STATUS_ACTION action=1;
	STATUS_TYPE type=2;
	int32 id=3;
	int32 value=4;
}

message StatusNotify
{
	repeated NSTATUS status=1; //repeated是数组 
}

////////////////////////////////////////////////////////////////
//
//  Entities实体
//
////////////////////////////////////////////////////////////////


message NEntity {
	int32 id = 1;
	NVector3 position = 2;
	NVector3 direction = 3;
	int32 speed = 4;
}

message NEntitySync {
	int32 id = 1;
	ENTITY_EVENT event = 2;
	NEntity entity = 3;
	int32 param=4;//参数
	
}



////////////////////////////////////////////////////////////////
//
//  Messages
//
////////////////////////////////////////////////////////////////

message NetMessage{
	NetMessageRequest Request = 1;
	NetMessageResponse Response = 2;
}

message NetMessageRequest{
	UserRegisterRequest userRegister = 1;
	UserLoginRequest userLogin = 2;
	UserCreateCharacterRequest createChar = 3;
	UserDeleteCharacterRequest deleteChar = 4;
	UserGameEnterRequest gameEnter = 5;
	UserGameLeaveRequest gameLeave = 6;
	
	MapCharacterEnterRequest mapCharacterEnter = 7;

	MapEntitySyncRequest mapEntitySync = 9;
	MapTeleportRequest mapTeleport = 10;
	ItemBuyRequest itemBuy=11;
	ItemSellRequest itemSell=50;
	ItemEquipRequest itemEquip=12;

	QuestListRequest questList=13;//任务列表
	QuestAcceptRequest questAccept=14;//接受任务
	QuestSubmitRequest questSubmit=15;//提交任务
	QuestAbandonRequest questAbandon=16;//放弃任务

	//好友
	FriendAddRequest friendAddRequest=17;//双向
	FriendAddResponse friendAddResponse=18;
	FriendListRequest friendList=19;
	FriendRemoveRequest friendRemove=20;

	//组队
	TeamInviteRequest teamInviteRequest=21;
	TeamInviteResponse teamInviteResponse=22;
	TeamInfoRequest teamInfo=23;
	TeamLeaveRequest teamLeave=24;


	//公会
	GuildCreateRequest guildCreate=25;
	GuildJoinRequest guildJoinRequest=26;
	GuildJoinResponse guildJoinResponse=27;
	GuildListRequest guildList=28;
	GuildLeaveRequest guildLeave=29;
	GuildRequest guild=30;
	GuildAdminRequest guildAdmin=31;//管理协议
	ChatRequest chat=32;
}

message NetMessageResponse{
	UserRegisterResponse userRegister = 1;
	UserLoginResponse userLogin = 2;
	UserCreateCharacterResponse createChar = 3;
	UserDeleteCharacterResponse deleteChar = 4;
	UserGameEnterResponse gameEnter = 5;
	UserGameLeaveResponse gameLeave = 6;

	MapCharacterEnterResponse mapCharacterEnter = 7;
	MapCharacterLeaveResponse mapCharacterLeave = 8;

	MapEntitySyncResponse mapEntitySync = 9;
	ItemBuyResponse itemBuy=11;
	ItemSellResponse itemSell=50;
	ItemEquipResponse itemEquip=12;

	QuestListResponse questList=13;
	QuestAcceptResponse questAccept=14;
	QuestSubmitResponse questSubmit=15;//提交任务
	QuestAbandonResponse questAbandon=16;//放弃任务

	FriendAddRequest friendAddRequest=17;
	FriendAddResponse friendAddResponse=18;
	FriendListResponse friendList=19;
	FriendRemoveResponse friendRemove=20;

	//组队
	TeamInviteRequest teamInviteRequest=21;
	TeamInviteResponse teamInviteResponse=22;
	TeamInfoResponse teamInfo=23;
	TeamLeaveResponse teamLeave=24;


	//公会
	GuildCreateResponse guildCreate=25;
	GuildJoinRequest guildJoinRequest=26;
	GuildJoinResponse guildJoinResponse=27;
	GuildListResponse guildList=28;
	GuildLeaveResponse guildLeave=29;
	GuildResponse guild=30;
	GuildAdminResponse guildAdmin=31;
	ChatResponse chat=32;

	StatusNotify statusNotify=100;

	
}


// User Protocol

message UserLoginRequest {
	string user = 1;
	string passward = 2;
}

message UserLoginResponse {
	RESULT result = 1;
	string msg = 2;
	NUserInfo userinfo = 3;
}


message UserRegisterRequest
{
	string user = 1;
	string passward = 2;
}

message UserRegisterResponse {
	RESULT result = 1;
	string msg = 2;
}

message UserCreateCharacterRequest
{
	string name = 1;
	CHARACTER_CLASS class = 2;
}

message UserCreateCharacterResponse {
	RESULT result = 1;
	string msg = 2;
	repeated NCharacterInfo characters = 3;
}
message UserDeleteCharacterRequest
{
    int32 characterId = 1;
}

message UserDeleteCharacterResponse {
    RESULT result = 1;
    string msg = 2;
	string name = 3;
    repeated NCharacterInfo characters = 4;

}

message UserGameEnterRequest
{
	int32 characterIdx = 1;
}

message UserGameEnterResponse {
	RESULT result = 1;
	string msg = 2;
	NCharacterInfo character=3; //返回角色信息
}

message UserGameLeaveRequest
{
}

message UserGameLeaveResponse {
	RESULT result = 1;
	string msg = 2;
}

// Map Protocol
message MapCharacterEnterRequest
{
	int32 mapId = 1;
}

message MapCharacterEnterResponse
{
	int32 mapId = 1;
	repeated NCharacterInfo characters = 2;
}

message MapCharacterLeaveResponse
{
	int32 entityId = 1;
}


message MapEntitySyncRequest
{
    NEntitySync entitySync = 1;
}


message MapEntitySyncResponse
{
    repeated NEntitySync entitySyncs = 2;
}

message MapTeleportRequest
{
	int32 teleporterId = 1;
}

//道具购买请求
message ItemBuyRequest
{
	int32 shopID=1;
	int32 shopItemID=2;
}

//道具购买响应
message ItemBuyResponse
{
	RESULT result=1;
	string msg=2;
}

//道具购买请求
message ItemSellRequest
{
	int32 shopItemID=1;
	int32 sellCount=2;
}

//道具购买响应
message ItemSellResponse
{
	RESULT result=1;
	string msg=2;
}

//背包保存请求
message BagSaveRequest
{
	NBagInfo BagInfo=1;
}

//背包响应
message BagSaveResponse
{
	RESULT result=1;
	string msg=2;
}

//装备请求
message ItemEquipRequest
{
	int32 slot=1;
	int32 itemId=2;
	bool isEquip=3;//代表穿还是脱装备
}

message ItemEquipResponse
{
	RESULT result=1;
	string msg=2;
}

//任务系统

enum QUEST_STATUS
{
	IN_PROGRESS=0;//接受未完成
	COMPLATED=1;//已完成 未提交
	FINISHED=2;//已完成
	FAILED=3;//失败
}

enum QUEST_LIST_TYPE//任务列表的类型(不一定用得到)
{
	ALL=0;
	IN_PROGRESS=1;
	FINISHED=2;
}

message NQuestInfo
{
	int32 quest_id=1;//任务ID
	int32 quest_dbid=2;//对应数据库的ID 暂时用不到
	QUEST_STATUS status=3;//任务状态
	repeated int32 targets=4;
}

message QuestListRequest
{
	QUEST_LIST_TYPE listType=1;
}

message QuestListResponse
{
	RESULT result=1;
	string msg=2;
	repeated NQuestInfo quests=3;//任务内容
}

message QuestAcceptRequest//接受
{
	int32 quest_id=1;
}

message QuestAcceptResponse
{
	RESULT result=1;
	string msg=2;
	NQuestInfo quest=3;
}

message QuestSubmitRequest//提交
{
	int32 quest_id=1;
}

message QuestSubmitResponse
{
	RESULT result=1;
	string msg=2;
	NQuestInfo quest=3;
}

message QuestAbandonRequest//放弃
{
	int32 quest_id=1;
}

message QuestAbandonResponse
{
	RESULT result=1;
	string msg=2;
}


//好友系统
message NFriendInfo//好友信息
{
	int32 id=1;//数据库那条记录的ID
	NCharacterInfo friendInfo=2;
	int32 status=3;
}

message FriendAddRequest
{
	int32 from_id=1;//我的信息
	string from_name=2;
	int32 to_id=3;//我要加的人的信息
	string to_name=4;
}

message FriendAddResponse
{
	RESULT result=1;
	string msg=2;
	FriendAddRequest request=3;
}

message FriendListRequest
{

}

message FriendListResponse
{
	RESULT result=1;
	string msg=2;
	repeated NFriendInfo friends=3;
}

message FriendRemoveRequest
{
	int32 id=1;
	int32 frinedId=2;
}

message FriendRemoveResponse
{
	RESULT result=1;
	string msg=2;
	int32 id=3;
}

//组队系统
message NTeamInfo
{
	int32 id=1;
	int32 leader=2;//队长
	repeated NCharacterInfo members=3;
}

message TeamInviteRequest
{
	int32 team_id=1;//队伍Id
	int32 from_id=2;
	string from_name=3;
	int32 to_id=4;
	string to_name=5;
}

message TeamInviteResponse
{
	RESULT result=1;
	string msg=2;
	TeamInviteRequest request=3;
}

message TeamInfoRequest
{

}

message TeamInfoResponse
{
	RESULT result=1;
	string msg=2;
	NTeamInfo team=3;
}

message TeamLeaveRequest
{
	int32 team_id=1;
	int32 characterId=2;
}

message TeamLeaveResponse
{
	RESULT result=1;
	string msg=2;
	int32 characterId=3;
}


//公会

enum GUILD_TITLE
{
	NONE=0;//普通成员
	VICE_PRESIDENT=1;//副会长
	PRESIDENT=2;//会长
}

enum APPLY_RESULT
{
	NONE=0;
	ACCEPT=1;
	REJECT=2;
}

message NGuildInfo
{
	int32 id=1;//公会ID
	string guild_name=2;//公会名称
	int32 leaderId=3;//会长ID
	string leaderName=4;//会长名称
	string notice=5;//公会宗旨
	int32 memberCount=6;//公会人数
	repeated NGuildMemberInfo members=7;//成员列表
	repeated NGuildApplyInfo applies=8;//申请加入的信息
	int64 createTime=9;//创建时间
}

//成员信息
message NGuildMemberInfo
{
	int32 id=1;
	int32 characterId=2;
	GUILD_TITLE position=3;//职位
	NCharacterInfo info=4;//角色信息
	int64 joinTime=5;//加入时间
	int64 lastTime=6;//上次在线时间
	int32 status=7;//在线状态
}


//申请信息
message NGuildApplyInfo
{
	int32 guild_id=1;
	int32 characterId=2;
	string name=3;
	int32 class=4;
	int32 level=5;
	APPLY_RESULT result=6;
}

//创建公会
message GuildCreateRequest
{
	string guild_name=1;//公会名字
	string guild_notice=2;//公会宣言
}

message GuildCreateResponse
{
	RESULT result=1;
	string msg=2;
	NGuildInfo guild=3;
}

//加入公会申请[成员->服务器->会长]
message GuildJoinRequest
{
	NGuildApplyInfo apply=1;
}

message GuildJoinResponse//[服务器->会长]
{
	RESULT result=1;
	string msg=2;
	NGuildApplyInfo apply=3;
}

//公会列表
message GuildListRequest
{

}

message GuildListResponse
{
	RESULT result=1;
	string msg=2;
	repeated NGuildInfo guilds=3;
}


//公会信息
message GuildRequest
{

}

message GuildResponse
{
	RESULT result=1;
	string msg=2;
	NGuildInfo guild=3;
}

//离开公会
message GuildLeaveRequest
{
	int32 guild_id=1;
	int32 characterId=2;
}

message GuildLeaveResponse
{
	RESULT result=1;
	string msg=2;
}

//公会管理
enum GUILD_ADMIN_COMMAND
{
	KICKOUT=1;//踢人
	PROMOTE=2;//晋升
	DEPOSE=3;//罢免
	TRANSFER=4;//转让会长
}

message GuildAdminRequest
{
	GUILD_ADMIN_COMMAND command=1;
	int32 target=2;
}

message GuildAdminResponse
{
	RESULT result=1;
	string msg=2;
	GuildAdminRequest commandRequest=3;
}




//聊天
enum CHAT_CHANNEL
{
	ALL=-1;//综合
	LOCAL=1;//本地
	WORLD=2;//世界
	SYSTEM=4;//系统
	PRIVATE=8;//私聊
	TEAM=16;//队伍
	GUILD=32;//公会
}

message ChatMessage
{
	CHAT_CHANNEL channel=1;
	int32 id=2;
	int32 from_id=3;
	string from_name=4;
	int32 to_id=5;
	string to_name=6;
	string message=7;
	double time=8;
}

message ChatRequest
{
	ChatMessage message=1;
}

message ChatResponse
{
	RESULT result=1;
	string msg=2;
	repeated ChatMessage localMessages=3;
	repeated ChatMessage worldMessages=4;
	repeated ChatMessage systemMessages=5;
	repeated ChatMessage privateMessages=6;
	repeated ChatMessage teamMessages=7;
	repeated ChatMessage guildMessages=8;
}
